.section .text.init
.global _start
_start:
  addi x1, x0, 0
  addi x2, x0, 1
  add  x3, x1, x2

  addi x4, x0, 0
  addi x5, x0, 1
  add  x6, x4, x5

  addi x7, x0, 0
  addi x8, x0, 0
  addi x9, x0, 0
  addi x10, x0, 0
  addi x11, x0, 0
  addi x12, x0, 0
  
  addi x1, x2, 0
  addi x2, x3, 0
  add  x3, x1, x2
  
  addi x4, x5, 0
  addi x5, x6, 0
  add  x6, x4, x5

  addi x1, x2, 0
  addi x2, x3, 0
  add  x3, x1, x2

  addi x4, x5, 0
  addi x5, x6, 0
  add  x6, x4, x5

  addi x1, x2, 0
  addi x2, x3, 0
  add  x3, x1, x2

  addi x4, x5, 0
  addi x5, x6, 0
  add  x6, x4, x5

#  addi x1, x2, 0
#  addi x2, x3, 0
#  add  x3, x1, x2
#
#  addi x4, x5, 0
#  addi x5, x6, 0
#  add  x6, x4, x5
#
#  addi x1, x2, 0
#  addi x2, x3, 0
#  add  x3, x1, x2
#
#  addi x4, x5, 0
#  addi x5, x6, 0
#  add  x6, x4, x5
#
#  addi x1, x2, 0
#  addi x2, x3, 0
#  add  x3, x1, x2
#
#  addi x4, x5, 0
#  addi x5, x6, 0
#  add  x6, x4, x5
#
#  addi x1, x2, 0
#  addi x2, x3, 0
#  add  x3, x1, x2
#
#  addi x4, x5, 0
#  addi x5, x6, 0
#  add  x6, x4, x5
#
